version: "2"
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
      - MYSQL_DATABASE=jbuster
    ports:
      - 4285:3306
  app:
    build:
      context: ./web
    ports:
      - 4280:8080
      - 4281:9990
    depends_on:
      - db
    dns: 8.8.8.8
